language: python
python:
  - "3.6.2"
services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database mydiary;' -U postgres
  - psql -c 'create database mydiary_test;' -U postgres

script: nosetests --with-coverage ./v1/tests

after_success:
  - coveralls
