FORMAT: 1A
HOST: https://ch3-api.herokuapp.com

# MyDiary API

This is an API built to power MyDiary--a platform that allows users to write down their thoughts and feelings.

A user is required to first sign up after which they'll be able to login with their email and password. Users' diary endpoints are protected using token-based authentication.


# API Features

Users can:
* Register
* Login
* Add new diary entries
* View their diary entries
* Modify diary entries
* Delete diary entries


# Group Users

## User Signup [/api/v1/auth/signup/]

A user signs-up by providing: firstname,lastname,username,email,password

### Register a user [POST]

+ Request (application/json)

            {
                 "firstname": "Kapere",
                 "lastname": "Angellina",
                 "username": "kange",
                 "email": "kange@email.com",
                 "password": "letMePAss000"
            }

+ Response 201 (application/json)

    + Body

            {
                "message": "user registered successfully. ",
                "status": "success"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": {
                    "error": "The following fields had invalid data: firstname",
                    "help": "firstname -> The firstname must be a valid string 2-30 characters long. "
                },
                "status": "failed"
            }

## User Login [/api/v1/auth/login/]

A user logs-in by providing a registered email and password.
Take note of the access token since it will be required to access the diary endpoints

### Login [POST]

+ Request (application/json)

            {
                "email": "kange@email.com",
                "password": "letMePAss000"
            }

+ Response 200 (application/json)

    + Body

            {
                "message": "Logged in successfully. Take note of your access-token. You'll need it to authenticate your requests",
                "access-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.Hk4NIkv8GKWeuB7G3yjoxUlESFqz9JudGjKsywc6kSY"
            }

+ Response 401 (application/json)

    + Body

            {
                "message": "invalid login credencials",
                "status": "failed"
            }


# Group Entries

## Diary Entries [/api/v1/entries/]

### Register A New Entry [POST]

+ Header

    access-token: JWT Token


+ Request (application/json)

    + Body

            {
                "title": "this is my first title",
                "content": "this is the content"
            }

+ Response 201 (application/json)

    + Body

            {
                "message": "new diary entry added. ",
                "status": "success"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "The following fields were missing in the data: content",
                "status": "fail"
            }

### List All Diary Entries [GET]

+ Header

    access-token: JWT Token


+ Response 200 (application/json)

    + Body

            {
                "Diary Entries": [
                    {
                        "content": "this is the content",
                        "created": "Thu, 09 Aug 2018 14:04:17 GMT",
                        "eid": 1,
                        "title": "this is my first title"
                    },
                    {
                        "content": "content for the second title",
                        "created": "Thu, 09 Aug 2018 14:04:52 GMT",
                        "eid": 2,
                        "title": "second title"
                    }
                ]
            }

+ Response 403 (application/json)

    + Body

            {
                "Error": "Token is missing"
            }


## Single Diary Entry [/api/v1/entries/<entryId>]

### Get A Single Diary Entry [GET]

+ Parameters

    + entryId (number) - ID of desired diary entry

+ Header

    access-token: JWT Token


+ Response 200 (application/json)

    + Body

            {
                "Diary Entry": {
                    "content": "this is the content",
                    "created": "Thu, 09 Aug 2018 14:04:17 GMT",
                    "eid": 1,
                    "title": "this is my first title"
                }
            }

+ Response 404 (application/json)

    + Body

            {
                "message": "entry with id:{entryId} not found",
                "status": "failed"
            }

+ Response 403 (application/json)

    + Body

            {
                "Error": "Token is missing"
            }


### Modify An Entry [PUT]

+ Parameters

    + entryId (number) - ID of desired diary entry

+ Header

    access-token: JWT Token


+ Request (application/json)

    + Body

            {

                "title": "this is a modified title",
                "content": "this is the modified content"
            }

+ Response 202 (application/json)

    + Body

            {
                "message": "diary entry modified successfully. ",
                "status": "success"
            }

+ Response 404 (application/json)

    + Body

            {
                "message": "entry with id:{entryId} not found",
                "status": "failed"
            }

+ Response 403 (application/json)

    + Body

            {
                "Error": "Token is missing"
            }

### Delete An Entry [DELETE]

+ Parameters

    + entryId (number) - ID of desired diary entry

+ Header

    access-token: JWT Token


+ Response 200 (application/json)

    + Body

            {
                "message": "entry deleted successfully",
                "status": "success"
            }

+ Response 404 (application/json)

    + Body

            {
                "message": "entry with id:{entryId} not found",
                "status": "failed"
            }

+ Response 403 (application/json)

    + Body

            {
                "Error": "Token is missing"
            }
